databases:
  - name: cv_db
    databaseName: cv_db
    user: cv_db

services:
  - type: web
    name: cv_db
    plan: starter
    region: oregon
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app.wsgi:application"
    autoDeploy: false
    envVars:
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: cv_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
